# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection:
        enabled: true  # Activation obligatoire pour les formulaires

    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions'
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 86400  # 1 jour
        gc_maxlifetime: 86400   # 1 jour

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file